exec sp_rename 'SYS_REST_API_TOKEN.ACCESS_TOKEN_VALUE', 'TOKEN_VALUE', 'COLUMN';
exec sp_rename 'SYS_REST_API_TOKEN.ACCESS_TOKEN_BYTES', 'TOKEN_BYTES', 'COLUMN';
alter table SYS_REST_API_TOKEN drop column CREATED_BY^