/*
 * Copyright (c) 2008-2016 Haulmont.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.haulmont.cuba.core.entity;

import javax.persistence.MappedSuperclass;
import javax.persistence.Transient;

/**
 * Base class for persistent entities with identifier generated by the database on insert.
 */
@MappedSuperclass
public abstract class BaseDbGeneratedIdEntity extends BaseGenericIdEntity<IdProxy> {

    @Transient
    protected IdProxy idProxy;

    @Override
    public IdProxy getId() {
        if (idProxy == null) {
            idProxy = new IdProxy(this);
        }
        return idProxy;
    }

    @Override
    public void setId(IdProxy idProxy) {
        setDbGeneratedId(idProxy.get());
    }

    protected abstract void setDbGeneratedId(Long dbId);

    protected abstract Long getDbGeneratedId();
}
