alter table SEC_ENTITY_LOG add STRING_ENTITY_ID varchar2(255)^
alter table SEC_ENTITY_LOG add INT_ENTITY_ID integer^
alter table SEC_ENTITY_LOG add LONG_ENTITY_ID number^

create index IDX_SEC_ENTITY_LOG_SENTITY_ID on SEC_ENTITY_LOG (STRING_ENTITY_ID)^
create index IDX_SEC_ENTITY_LOG_IENTITY_ID on SEC_ENTITY_LOG (INT_ENTITY_ID)^
create index IDX_SEC_ENTITY_LOG_LENTITY_ID on SEC_ENTITY_LOG (LONG_ENTITY_ID)^