alter table SEC_SCREEN_HISTORY add STRING_ENTITY_ID varchar(190);
alter table SEC_SCREEN_HISTORY add INT_ENTITY_ID integer;
alter table SEC_SCREEN_HISTORY add LONG_ENTITY_ID bigint;
create index IDX_SEC_SCREEN_HISTORY_ENTITY_ID on SEC_SCREEN_HISTORY (ENTITY_ID);
create index IDX_SEC_SCREEN_HISTORY_SENTITY_ID on SEC_SCREEN_HISTORY (STRING_ENTITY_ID);
create index IDX_SEC_SCREEN_HISTORY_IENTITY_ID on SEC_SCREEN_HISTORY (INT_ENTITY_ID);
create index IDX_SEC_SCREEN_HISTORY_LENTITY_ID on SEC_SCREEN_HISTORY (LONG_ENTITY_ID);