alter table SYS_QUERY_RESULT add STRING_ENTITY_ID varchar2(255)^
alter table SYS_QUERY_RESULT add INT_ENTITY_ID integer^
alter table SYS_QUERY_RESULT add LONG_ENTITY_ID number^
create index IDX_SYS_QUERY_RES_SEN_SES_KEY on SYS_QUERY_RESULT(STRING_ENTITY_ID, SESSION_ID, QUERY_KEY)^
create index IDX_SYS_QUERY_RES_IEN_SES_KEY on SYS_QUERY_RESULT(INT_ENTITY_ID, SESSION_ID, QUERY_KEY)^
create index IDX_SYS_QUERY_RES_LEN_SES_KEY on SYS_QUERY_RESULT(LONG_ENTITY_ID, SESSION_ID, QUERY_KEY)^