/*
 * Copyright (c) 2008 Haulmont Technology Ltd. All Rights Reserved.
 * Haulmont Technology proprietary and confidential.
 * Use is subject to license terms.

 * Author: Konstantin Krivopustov
 * Created: 20.05.2009 18:22:40
 *
 * $Id$
 */
package com.haulmont.cuba.web.exception;

import com.haulmont.cuba.web.App;
import com.vaadin.terminal.Terminal;

/**
 * Interface to be implemented by exception handlers in Web-client.
 *
 * <p>$Id$</p>
 *
 * @author krivopustov
 */
public interface ExceptionHandler
{
    /**
     * Handle an exception. Implementation class should either handle the exception and return true, or return false
     * to delegate execution to the next handler in the chain of responsibility.
     * @param event error event containing the exception, generated by Vaadin
     * @param app   current {@link App} instance
     * @return      true if the exception has been succesfully handled, false if not
     */
    boolean handle(Terminal.ErrorEvent event, App app);
}
